const ADD_COUNT = "ADD_COUNT";
const MINUS_COUNT = "MINUS_COUNT";
const SET_USERS = "SET_USERS";
const SET_MY_API_DATA = "SET_MY_API_DATA";
const APPEND_RESTAURANT_LIST = "APPEND_RESTAURANT_LIST";
const APPEND_ANALYZED_RESTAURANT_LIST = "APPEND_ANALYZED_RESTAURANT_LIST";
const EMPTY_RESTAURANT_LIST = "EMPTY_RESTAURANT_LIST";
const SET_RADIUS = "SET_RADIUS";
const GET_INPUT_LOCATION = "GET_INPUT_LOCATION";
const GET_SEARCH_INPUT = "GET_SEARCH_INPUT";
const APPEND_MEET_USER_DATA = "APPEND_MEET_USER_DATA";

const Action = {
  ADD_COUNT,
  MINUS_COUNT,
  SET_USERS,
  SET_MY_API_DATA,
  APPEND_RESTAURANT_LIST,
  APPEND_ANALYZED_RESTAURANT_LIST,
  EMPTY_RESTAURANT_LIST,
  SET_RADIUS,
  GET_INPUT_LOCATION,
  GET_SEARCH_INPUT,
  APPEND_MEET_USER_DATA,
};

export default Action;
