const ADD_COUNT = "ADD_COUNT";
const MINUS_COUNT = "MINUS_COUNT";
const SET_USERS = "SET_USERS";
const SET_MY_API_DATA = "SET_MY_API_DATA";
const UPDATE_RESTAURANT_LIST = "UPDATE_RESTAURANT_LIST";

const Action = {
  ADD_COUNT,
  MINUS_COUNT,
  SET_USERS,
  SET_MY_API_DATA,
  UPDATE_RESTAURANT_LIST,
};

export default Action;
